#!/usr/bin/env bash
# Transfer file from client local server to remote server

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scq -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=dev/null -i "$4" "$1" "$3@$2":~/
