#!/usr/bin/env bash
# Transfer file from client local server to remote server
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

fi

scp -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=dev/null -i "$4" "$1" "$3@$2":~/
