#!/usr/bin/env bash
# Configures new Ubuntu machine to respect above requirements
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# code to redirect to YouTube site (Ex. redirect_me to www.youtube.com)
echo 'Hello World!' > /var/www/html/index.html
newString="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$newString/" /etc/nginx/sites-enabled/default

# restart the server
service nginx restart
