#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Maske sure that HAproxy can be managed via an init script

# Install HAproxy
sudo apt-get update
apt-get -y install haproxy=2.6.\*

# Configure frontend & Backend
configString=\
"
frontend onirele-frontend
        bind *:80
        mode http
        default_backend onirele-backend
backend onirele-backend
        balance roundrobin
        server 68701-web-01 54.165.12.83:80 check
        server 68701-web-02 54.237.93.128:80 check
"
echo "$configString" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable the HAproxy init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start
