#!/usr/bin/env bash
# This script is displays bad luck on 4th loop iteration,
#+ displays good luck on the 8th iteration,
#+ displays Best School for the other iterations

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
