#!/usr/bin/env bash
# This script is displays bad luck from China on 4th loop iteration,
#+ displays bad luck from Japan on the 9th loop iteration,
#+ displays bad luck from Italy on the 17th loop iteration

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( count++))
done
