#!/usr/bin/env bash
# This script is displays,
#+ content of the current directory,
#+ Only part of the name after the first dash displayed

LIST=$(ls)
for i in $LIST
do
	echo "$i" | cut -d '-' -f 2
done
